ARG BASE_IMAGE
FROM ${BASE_IMAGE}
ARG R_VERSION
ARG BIOC_VERSION
ARG BIOC_DOCKER_VERSION
ARG RSTUDIO_URL

# Set Bioconductor environment variables
ENV BIOCONDUCTOR_VERSION=${BIOC_VERSION}
ENV BIOCONDUCTOR_DOCKER_VERSION=${BIOC_DOCKER_VERSION}

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gfortran \
    libreadline-dev \
    libx11-dev \
    libxt-dev \
    libpng-dev \
    libjpeg-dev \
    libcairo2-dev \
    libssl-dev \
    libbz2-dev \
    liblzma-dev \
    libpcre2-dev \
    libcurl4-openssl-dev \
    libxml2-dev \
    ca-certificates \
    wget \
    && wget https://cran.r-project.org/src/base/R-4/R-${R_VERSION}.tar.gz \
    && tar -xzvf R-${R_VERSION}.tar.gz \
    && cd R-${R_VERSION} \
    && ./configure --enable-R-shlib --with-readline --with-blas --with-lapack \
    && make -j$(nproc) \
    && make install \
    && cd .. \
    && rm -rf R-${R_VERSION}.tar.gz R-${R_VERSION} \
    && Rscript -e "BiocManager::install(version='${BIOC_VERSION}', ask = FALSE)"

RUN apt-get update && apt-get install -y --no-install-recommends \
    gdebi-core \
    && wget ${RSTUDIO_URL} -O rstudio-server.deb \
    && gdebi -n rstudio-server.deb \
    && rm rstudio-server.deb
